"""create rooms table

Revision ID: 471b7ac1f651
Revises: cf56ecc91fbd
Create Date: 2026-08-20 08:45:53.390563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471b7ac1f651'
down_revision: Union[str, Sequence[str], None] = 'cf56ecc91fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('roon_number', sa.String(), nullable=False),
    sa.Column('occupied_bed', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pg_id'], ['pgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
